### Ex 3.1

In [1]:
import numpy as np

A = np.array([1,2,3])
B = np.array([1,2,3])
C = np.array([2,1,3])

print("A == B", A == B)
print("A == C", A == C)
print("A > C", A > B)

A == B [ True  True  True]
A == C [False False  True]
A > C [False False False]


### Ex 3.2

In [2]:
import numpy as np

def funktion(x):
    return x*x + 1

A = np.array([1,2,3])
B = funktion(A)
print(B)

[ 2  5 10]


### Ex 3.3

In [3]:
import numpy as np

Checker_board_array = np.zeros((8,8))
Checker_board_array[1::2,::2] = 1
Checker_board_array[::2,1::2] = 1
print(Checker_board_array)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


### Ex 3.4

In [4]:
import numpy as np

def value_equal_row_index(some_array):
    for i in range(0, len(some_array)):
        some_array[i,:] = i
    return some_array

A = np.zeros((6,6))
A = value_equal_row_index(A)
print(A)

[[0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2. 2.]
 [3. 3. 3. 3. 3. 3.]
 [4. 4. 4. 4. 4. 4.]
 [5. 5. 5. 5. 5. 5.]]


### Ex 3.5

In [5]:
import numpy as np

def remove_numbers(some_array, remove_from, remove_to):
    return some_array[np.logical_not(np.logical_and(some_array>=remove_from, some_array<=remove_to))]

A = np.arange(0, 100, 1)
A = remove_numbers(A, 10, 33)
print(A)


[ 0  1  2  3  4  5  6  7  8  9 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


### Ex 3.6

In [7]:
opened_file = open("data/file_for_exercise.txt","r")
print(opened_file)
opened_file.close()

<_io.TextIOWrapper name='data/file_for_exercise.txt' mode='r' encoding='UTF-8'>


### Ex 3.7

In [8]:
opened_file = open("data/file_for_exercise.txt","r")
readable_file = list(opened_file)
for line in readable_file:
    print(line)
opened_file.close()

I am a file.

I have no real content.

Here are some numbers:

1

2

3

4

5

6

7

8

9

10


### Ex 3.8

In [9]:
opened_file = open("data/file_for_exercise.txt","r")
readable_file = list(opened_file)

number_characters = 0
for line in readable_file:
    for character in line:
        number_characters += 1
print(number_characters)
opened_file.close()

80


### Ex 3.9

In [15]:
opened_file = open("data/file_for_exercise.txt","r")
readable_file = list(opened_file)

sum_of_numbers = 0
for line in readable_file:
    for item in line.split():
        # Found .isdigit() by using google. Google is your friend!
        if item.isdigit() == True:
            sum_of_numbers += float(line)
print(sum_of_numbers)
opened_file.close()

55.0


### Ex 3.10

In [20]:
opened_file = open("newfile.txt","w+")
opened_file.write("I am a newly written file")
opened_file.close()