### Ex 2.1

In [1]:
d = {0:10, 1:20}
print(d)
d[2] = 30
print(d)

{0: 10, 1: 20}
{0: 10, 1: 20, 2: 30}


### Ex 2.2

In [4]:
dic1={1:10, 2:20}
dic2={3:30, 4:40}
dic3={5:50,6:60}
dic4 = {}
for d in (dic1, dic2, dic3):
    dic4.update(d)
print(dic4)

{1: 10, 2: 20, 3: 30, 4: 40, 5: 50, 6: 60}


### Ex 2.3

In [6]:
dic = {1: 10, 2: 20, 3: 30, 4: 40, 5: 50, 6: 60}
print(3 in dic)
print(10 in dic)

True
False


### Ex 2.4

In [7]:
def three_largest(dictionary):
    values = []
    for key in dictionary:
        values.append(dictionary[key])
    values.sort(reverse=True)
    return values[0:3]

dic = {"A": 10, "B": 20, "C": 300, "D": 40, "E": 61, "F": 60}
three_largest(dic)

[300, 61, 60]

### Ex 2.5


In [10]:
def fibonacci(x, y):
    fib_numbers = [0, 1]
    while fib_numbers[-1] < y:
        if fib_numbers[-1] >= x:
            print(fib_numbers[-1])
        fib_numbers.append(fib_numbers[-1] + fib_numbers[-2])

fibonacci(10, 200)

13
21
34
55
89
144


### Ex 2.6

In [19]:
def fizzbuzz(x):
    for i in range(1, x+1):
        if i % 3 == 0 and i % 5 == 0:
            print("fizzbuzz")
        elif i % 3 == 0:
            print("fizz")
        elif i % 5 == 0:
            print("buzz")
        else:
            print(i)
        
fizzbuzz(25)

1
2
fizz
4
buzz
fizz
7
8
fizz
buzz
11
fizz
13
14
fizzbuzz
16
17
fizz
19
buzz
fizz
22
23
fizz
buzz


### Ex 2.7

In [20]:
def multiplication_table(number, x, y):
    for i in range(x, y+1):
        print(number,'x',i,'=',number*i)
        
multiplication_table(27, 7, 13)

27 x 7 = 189
27 x 8 = 216
27 x 9 = 243
27 x 10 = 270
27 x 11 = 297
27 x 12 = 324
27 x 13 = 351


### Ex 2.8

In [23]:
def find_prime(x):
    i = 0
    prime_list = []
    while True:
        i += 1
        not_prime = 0
        for j in prime_list:
            if i%j == 0 and j != 1:
                not_prime = 1
                break
        if not_prime == 0:
            print(i)
            prime_list.append(i)
        
        if len(prime_list) == x:
            break

find_prime(10)

1
2
3
5
7
11
13
17
19
23


### Ex 2.9

In [24]:
def factorial_recursion(n):
    if n < 1:
        return 1
    else:
        return n*factorial_recursion(n-1)
    
def factorial_loops(n):
    factorial = 1
    for i in range(1, n+1):
        factorial *= i
    return factorial
    
print(factorial_recursion(7))
print(factorial_loops(7))

5040
5040


### Ex 2.10

In [28]:
import numpy as np

li = [12.23, 13.32, 100, 36.32]
li_numpy = np.array(li)
li_numpy

array([ 12.23,  13.32, 100.  ,  36.32])

### Ex 2.11

In [30]:
import numpy as np
x = np.arange(2, 11).reshape(3,3)
print(x)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


### Ex 2.12

In [35]:
array_with_vals(3, 13, 0.01)

array([ 3.  ,  3.01,  3.02,  3.03,  3.04,  3.05,  3.06,  3.07,  3.08,
        3.09,  3.1 ,  3.11,  3.12,  3.13,  3.14,  3.15,  3.16,  3.17,
        3.18,  3.19,  3.2 ,  3.21,  3.22,  3.23,  3.24,  3.25,  3.26,
        3.27,  3.28,  3.29,  3.3 ,  3.31,  3.32,  3.33,  3.34,  3.35,
        3.36,  3.37,  3.38,  3.39,  3.4 ,  3.41,  3.42,  3.43,  3.44,
        3.45,  3.46,  3.47,  3.48,  3.49,  3.5 ,  3.51,  3.52,  3.53,
        3.54,  3.55,  3.56,  3.57,  3.58,  3.59,  3.6 ,  3.61,  3.62,
        3.63,  3.64,  3.65,  3.66,  3.67,  3.68,  3.69,  3.7 ,  3.71,
        3.72,  3.73,  3.74,  3.75,  3.76,  3.77,  3.78,  3.79,  3.8 ,
        3.81,  3.82,  3.83,  3.84,  3.85,  3.86,  3.87,  3.88,  3.89,
        3.9 ,  3.91,  3.92,  3.93,  3.94,  3.95,  3.96,  3.97,  3.98,
        3.99,  4.  ,  4.01,  4.02,  4.03,  4.04,  4.05,  4.06,  4.07,
        4.08,  4.09,  4.1 ,  4.11,  4.12,  4.13,  4.14,  4.15,  4.16,
        4.17,  4.18,  4.19,  4.2 ,  4.21,  4.22,  4.23,  4.24,  4.25,
        4.26,  4.27,

### Ex 2.13

In [36]:
def zero_on_the_inside(size):
    x = np.ones((size,size))
    x[1:-1,1:-1] = 0
    return x

zero_on_the_inside(7)

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])