## Ex 4.1 - Quadratic Equation Solver
In this exercise we will write a quadratic equation solver.
We know the equation form the exercise.

In [3]:
def quadratic_solver(a, b, c):
    # The two solutions are calculated.
    # ()**0.5 is the square root
    x1 = -(b + (b**2 - 4*a*c)**0.5)
    x2 = -(b - (b**2 - 4*a*c)**0.5)
    return x1, x2

In [4]:
# Some results
print(quadratic_solver(1, 2, -2))
print(quadratic_solver(1, 1, 0))

(-5.464101615137754, 1.4641016151377544)
(-2.0, -0.0)


In [5]:
quadratic_solver(1, 1, 1)

((-1-1.7320508075688772j), (-0.9999999999999999+1.7320508075688772j))

We can see that complex numbers are a part of Python.
But we are still to print an error if a real solution is undefined.

In [11]:
def quadratic_solver_2(a, b, c):
    D = b**2 - 4*a*c
    if D < 0: # Checking if a real solution exists
        print("Error, no real solution")
    else:
        # Since b**2 - 4*a*c is already calculted, it can be used here too.
        x1 = -(b + (D)**0.5)
        x2 = -(b - (D)**0.5)
        return x1, x2

In [12]:
quadratic_solver_2(1, 1, 1)

Error, no real solution


## Ex 4.2 - Pig Latin Translator
In this exercise we will work with strings.

In [53]:
def pig_latin_translator(our_string):
    # Making an empty list to store the pig latin words in
    pig_latin_word = []
    # Making a list of all the vowels. Could also have been a list with the
    #  consonants. But this list is shorter.
    vowels = ["a","e","i","o","u","y"]
    # Making our string into a list of words
    word_list = our_string.split()
    # Looping all the words
    for word in word_list:
        # Making a counter to count all the consonant comming before the
        #  first vowel. Since it is under a for loop, it will be set to zero
        #  again for every word.
        number_consontants = 0
        if word[0] not in vowels: # Checks if the first letter is a consonant.
            for letter in word:
                if letter not in vowels:
                    number_consontants += 1
                else:
                    break
        # Time to make the pig latin word
        if number_consontants == 0:
            pig_latin_word.append(word+"way")
        else:
            pig_latin_word.append(word[number_consontants:]+word[0:number_consontants]+"ay")
            
    return pig_latin_word

In [54]:
some_string = "Quadratic equations can be solved by a process known in American English as factoring and in other varieties of English as factorising, by completing the square, by using the quadratic formula, or by graphing."
print(pig_latin_translator(some_string))

['uadraticQay', 'equationsway', 'ancay', 'ebay', 'olvedsay', 'ybay', 'away', 'ocesspray', 'ownknay', 'inway', 'ericanAmay', 'ishEnglay', 'asway', 'actoringfay', 'andway', 'inway', 'otherway', 'arietiesvay', 'ofway', 'ishEnglay', 'asway', 'actorising,fay', 'ybay', 'ompletingcay', 'ethay', 'uare,sqay', 'ybay', 'usingway', 'ethay', 'uadraticqay', 'ormula,fay', 'orway', 'ybay', 'aphing.gray']


We can see we have some unwanted behaviour, fx. "uadraticQay" and "uare,sqay". Now lets try to fix this.

In [55]:
def pig_latin_translator_2(our_string):
    pig_latin_word = []
    vowels = ["a","e","i","o","u","y"]
    special_char = [",","."]
    # We can use .lower() to make all letters lower case.
    word_list = our_string.lower().split()
    for word in word_list:
        number_consontants = 0
        check_special_char = 0 
        if word[-1] in special_char:
            # Here we check if there is a special character present.
            # Then the variable check_special_char is set to one, so 
            #  we can remember for later in the code.
            check_special_char = 1
        if word[0] not in vowels:
            for letter in word:
                if letter not in vowels:
                    number_consontants += 1
                else:
                    break
        if number_consontants == 0 and check_special_char == 1:
            # If we found a special char in the back of the word, we make sure to put it last
            pig_latin_word.append(word[:-1]+"way"+word[-1])
        elif number_consontants == 0:
            pig_latin_word.append(word+"way")
        elif check_special_char == 1:
            pig_latin_word.append(word[number_consontants:-1]+word[0:number_consontants]+"ay"+word[-1])
        else:
            pig_latin_word.append(word[number_consontants:]+word[0:number_consontants]+"ay")
            
    return pig_latin_word

In [56]:
some_string = "Quadratic equations can be solved by a process known in American English as factoring and in other varieties of English as factorising, by completing the square, by using the quadratic formula, or by graphing."
print(pig_latin_translator_2(some_string))

['uadraticqay', 'equationsway', 'ancay', 'ebay', 'olvedsay', 'ybay', 'away', 'ocesspray', 'ownknay', 'inway', 'americanway', 'englishway', 'asway', 'actoringfay', 'andway', 'inway', 'otherway', 'arietiesvay', 'ofway', 'englishway', 'asway', 'actorisingfay,', 'ybay', 'ompletingcay', 'ethay', 'uaresqay,', 'ybay', 'usingway', 'ethay', 'uadraticqay', 'ormulafay,', 'orway', 'ybay', 'aphinggray.']


## Ex 4.3 - Counting words

In [26]:
# Loading in the text file
file = open("data/wannabe.txt")
text = file.read()

In [31]:
def word_counter(some_string):
    word_list = some_string.split()
    # We can use a dictionary to keep track of the number of different 
    #  words we have found
    word_counter = {}
    for word in word_list:
        # Check if we have found word alrady.
        #  If yes then we increase the count by one.
        if word in word_counter:
            word_counter[word] += 1
        else:
            # Else we make an entry for the word, in our dict.
            word_counter[word] = 1
    return word_counter

In [43]:
print(word_counter(text))

{'Ha': 1, 'ha': 6, 'Yo,': 1, "I'll": 6, 'tell': 8, 'you': 40, 'what': 17, 'I': 25, 'want,': 8, 'really,': 14, 'really': 12, 'want': 9, 'So': 4, 'me': 5, 'wanna,': 12, '(ha)': 12, 'wanna': 16, 'zigazig': 4, 'ah': 4, 'If': 11, 'my': 18, 'future,': 1, 'forget': 1, 'past': 1, 'get': 8, 'with': 8, 'me,': 3, 'better': 1, 'make': 1, 'it': 15, 'fast': 1, 'Now': 2, "don't": 1, 'go': 1, 'wasting': 1, 'precious': 1, 'time': 1, 'Get': 1, 'your': 8, 'act': 1, 'together': 1, 'we': 1, 'could': 1, 'be': 10, 'just': 1, 'fine': 1, 'lover,': 6, 'gotta': 5, 'friends': 3, '(Gotta': 3, 'friends)': 3, 'Make': 3, 'last': 4, 'forever,': 3, 'friendship': 3, 'never': 3, 'ends': 3, 'have': 3, 'got': 7, 'to': 6, 'give': 4, 'Taking': 3, 'is': 6, 'too': 3, 'easy,': 3, 'but': 3, "that's": 3, 'the': 4, 'way': 3, 'Oh,': 1, 'do': 1, 'think': 1, 'about': 1, 'that': 1, 'know': 1, 'how': 1, 'feel': 1, 'Say,': 1, 'can': 1, 'handle': 1, 'love,': 1, 'are': 1, 'for': 4, 'real': 2, '(Are': 1, 'real)': 1, "won't": 1, 'hasty,': 1

We have the same problem as for the pig latin translator.

In [46]:
def word_counter_2(some_string):
    word_list = some_string.lower().split()
    word_counter = {}
    special_char = [",",".","(",")"]
    for word in word_list:
        check_special_char_back = 0
        check_special_char_front = 0
        # Checking for special chars
        if word[-1] in special_char:
            check_special_char_back = 1
        if word[0] in special_char:
            check_special_char_front = 1
        
        # Know only getting the part of the word without special chars.
        if word[check_special_char_front:len(word)-check_special_char_back] in word_counter:
            word_counter[word[check_special_char_front:len(word)-check_special_char_back]] += 1
        else:
            word_counter[word[check_special_char_front:len(word)-check_special_char_back]] = 1

    return word_counter

In [47]:
print(word_counter_2(text))

{'ha': 23, 'yo': 2, "i'll": 6, 'tell': 8, 'you': 43, 'what': 17, 'i': 25, 'want': 17, 'really': 26, 'so': 5, 'me': 8, 'wanna': 28, 'zigazig': 4, 'ah': 4, 'if': 11, 'my': 18, 'future': 1, 'forget': 1, 'past': 1, 'get': 9, 'with': 8, 'better': 1, 'make': 5, 'it': 15, 'fast': 1, 'now': 2, "don't": 1, 'go': 1, 'wasting': 1, 'precious': 1, 'time': 1, 'your': 8, 'act': 1, 'together': 1, 'we': 2, 'could': 1, 'be': 10, 'just': 1, 'fine': 1, 'lover': 8, 'gotta': 12, 'friends': 6, 'last': 4, 'forever': 4, 'friendship': 3, 'never': 3, 'ends': 3, 'have': 3, 'got': 7, 'to': 6, 'give': 6, 'taking': 3, 'is': 6, 'too': 3, 'easy': 4, 'but': 3, "that's": 3, 'the': 4, 'way': 3, 'oh': 1, 'do': 1, 'think': 1, 'about': 1, 'that': 1, 'know': 1, 'how': 1, 'feel': 1, 'say': 2, 'can': 1, 'handle': 1, 'love': 1, 'are': 2, 'for': 4, 'real': 3, "won't": 1, 'hasty': 1, 'a': 5, 'try': 1, 'bug': 1, 'then': 1, 'goodbye': 1, "you've": 2, "here's": 1, 'story': 1, 'from': 1, 'z': 1, 'listen': 1, 'carefully': 1, 'em': 1, 

## Ex 4.4 - Matrix Transposer

In [49]:
import numpy as np

def matrix_transposer(matrix):
    # Making an empty matrix for later use
    # len(matrix) is the size of the first dimension
    # len(matrix[0]) is the size of the second dimension
    output_matrix = np.zeros((len(matrix),len(matrix[0])))
    for i in range(0, len(matrix)):
        for j in range(0, len(matrix[0])):
            # Now by the definition of matrix transpose
            output_matrix[i,j] = matrix[j,i]
    return output_matrix

In [51]:
A = np.array([[2,3,1],[1,3,6],[6,7,6]])
print(A)
print(matrix_transposer(A))

[[2 3 1]
 [1 3 6]
 [6 7 6]]
[[2. 1. 6.]
 [3. 3. 7.]
 [1. 6. 6.]]


## Ex 4.5 - Matrix Multiplier

In [60]:
import numpy as np

def matrix_multiplier(matrix_A, matrix_B):
    matrix_C = np.zeros((len(matrix_A),len(matrix_B[0])))
    for i in range(0, len(matrix_A)):
        for j in range(0, len(matrix_B[0])):
            for k in range(0, len(matrix_A[0])):
                # From the definition of matrix multiplication
                matrix_C[i,j] += matrix_A[i,k]*matrix_B[k,j]
    return matrix_C

In [61]:
A = np.array([[1,2,3],[4,5,6]])
B = np.array([[7,8],[9,10],[11,12]])
print(matrix_multiplier(A, B))

[[ 58.  64.]
 [139. 154.]]


In [62]:
# The function breaks if the matrices does not match in dimension.
# Giving an error that can be hard to understand
A = np.array([[1,2,3],[4,5,6]])
B = np.array([[7,8],[9,10]])
print(matrix_multiplier(A, B))

IndexError: index 2 is out of bounds for axis 0 with size 2

In [64]:
import numpy as np

def matrix_multiplier(matrix_A, matrix_B):
    if len(matrix_A[0]) == len(matrix_B):
        matrix_C = np.zeros((len(matrix_A),len(matrix_B[0])))
        for i in range(0, len(matrix_A)):
            for j in range(0, len(matrix_B[0])):
                for k in range(0, len(matrix_A[0])):
                    # From the definition of matrix multiplication
                    matrix_C[i,j] += matrix_A[i,k]*matrix_B[k,j]
        return matrix_C
    else:
        print("Error matrix dimensions does not match")

In [65]:
A = np.array([[1,2,3],[4,5,6]])
B = np.array([[7,8],[9,10]])
print(matrix_multiplier(A, B))

Error matrix dimensions does not match
None


## Ex 4.6 - Brute Forcing Probabilities

In [71]:
# Remember the last number is NOT included
dice_rolls = []
for i in range(1, 7):
    for j in range(1, 7):
        dice_rolls.append([i, j])

number_sixes = 0
for rolls in dice_rolls:
    if 6 in rolls:
        number_sixes +=1

print(number_sixes/len(dice_rolls))

0.3055555555555556


In [75]:
dice_rolls = []
for i in range(1, 7):
    for j in range(1, 7):
        for k in range(1, 7):
            for l in range(1, 7):
                for m in range(1, 7):
                    for n in range(1, 7):
                        dice_rolls.append([i, j, k, l, m, n])

wanted_rolls = 0
for rolls in dice_rolls:
    number_sixes_in_roll = 0
    # Finds how many sixes present in a given roll sequence.
    for number in rolls:
        if number == 6:
            number_sixes_in_roll +=1
    # If exactly one six is present, this is what we want
    if number_sixes_in_roll == 1:
        wanted_rolls += 1

print(wanted_rolls/len(dice_rolls))

0.4018775720164609


## Ex 4.7 - Estimating $\pi$ with random numbers

In [78]:
import numpy as np

number_random_numbers = 0
number_inside_circle = 0
# Number of times we pick a random number
for i in range(100000):
    number_random_numbers += 1
    x_coordinate = np.random.uniform(-1, 1)
    y_coordinate = np.random.uniform(-1, 1)
    # Using the equation from the exercise
    if (x_coordinate**2+y_coordinate**2)**0.5 <= 1:
        number_inside_circle += 1

print("Pi estimate:",4*number_inside_circle/number_random_numbers)

Pi estimate: 3.13912


## Ex 4.8 - The birthday "paradox"

In [89]:
import numpy as np

def birthday_problem_estimator(number_people):
    number_same_birthday = 0
    number_tries = 0
    for i in range(10000):
        number_tries += 1
        birthdays = np.zeros(number_people)
        # Assigning random birthdays
        for j in range(0, len(birthdays)):
            birthdays[j] = np.random.randint(1, 365)
        # Now checking if same birthday
        # The ranges are set so we dont check a person with itself
        found_match_check = 0
        for j in range(0, len(birthdays)-1):
            for k in range(j+1, len(birthdays)):
                if birthdays[j] == birthdays[k]:
                    number_same_birthday += 1
                    found_match_check = 1
                if found_match_check == 1:
                    # When we have found one match, then we dont 
                    #   need to search anymore
                    break
            if found_match_check == 1:
                break
        
    return number_same_birthday/number_tries

In [90]:
print(birthday_problem_estimator(2))
print(birthday_problem_estimator(23))
print(birthday_problem_estimator(30))

0.0038
0.507
0.7131
